### ISSUE TITLE
about running this program

### ISSUE THREAD

**Issue by daixixiwang** [NekoMimiUnagi/Strucutred-QA#4]
Hi, 
Could you fulfill the readme file to give more introduction on running this program? 

And the data is missing from this project, could you open the dataset used? 

Thanks!

**Comment by daixixiwang** [comment]
$ python src/preprocess.py
08/05/2024 22:20:36 - INFO - src.utils - Clean Finished
08/05/2024 22:20:36 - INFO - __main__ - Initializing dataset
08/05/2024 22:20:36 - INFO - src.dataset_reader - Reading 2wikimultihopqa_dev
Traceback (most recent call last):
  File "src/preprocess.py", line 140, in <module>
    dataset = StructureDataset(config['dataset_name'])
  File "src/preprocess.py", line 37, in __init__
    qa_pairs = read_data(dataset_name)
  File "/home/wangtingting/Structure-QA/src/dataset_reader.py", line 92, in read_data
    data = read_2wikimultihopqa(dataset_name)
  File "/home/wangtingting/Structure-QA/src/dataset_reader.py", line 68, in read_2wikimultihopqa
    with open(file_path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: **'data/2wikimultihop/sample_100_2wikimultihop_dev.json.bak2'**
